spring.application.name=sql

# SQLite
spring.datasource.url=jdbc:sqlite:${user.dir}/myapp.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

spring.session.store-type=none
spring.session.jdbc.initialize-schema=never

logging.level.org.springframework.jdbc=DEBUG
