CREATE TABLE IF NOT EXISTS CUSTOMERS (
                                         id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name         TEXT NOT NULL,
                                         surname      TEXT NOT NULL,
                                         age          INTEGER,
                                         phone_number TEXT,
                                         city         TEXT
);

CREATE TABLE IF NOT EXISTS ORDERS (
                                      id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      date         TEXT NOT NULL,
                                      customer_id  INTEGER NOT NULL,
                                      product_name TEXT NOT NULL,
                                      amount       INTEGER,
                                      CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id)
    );